# Generated by Django 4.1.1 on 2022-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(choices=[('Hot', 'Hot'), ('Normal', 'Normal'), ('Cold', 'Cold')], max_length=50, unique=True)),
                ('minimum_temperature', models.FloatField()),
                ('maximum_temperature', models.FloatField()),
            ],
        ),
    ]
